name: bluetooth_thermal_printer_example
description: Demonstrates how to use the bluetooth_thermal_printer plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  esc_pos_utils_plus: ^2.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  get: ^4.6.6
  lottie: ^3.1.3
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  animated_notch_bottom_bar: ^1.0.3
  fl_chart: ^0.69.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  dropdown_search: ^5.0.6
  qr_flutter: ^4.1.0
  blue_thermal_printer: ^1.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets\lottie\store.json
    - assets\image\aas_logo.png
    - assets\image\lockDeviceP\ld1.png
    - assets\image\lockDeviceP\ld2.png
    - assets\image\lockDeviceP\ld3.png
    - assets\image\notFoundW\notFound1.png
    - assets\image\notFoundW\notFound2.png
    - assets\image\loginP\bg.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
